import { MessageCardProps } from "@/components/data-card";

export const dataItems = [
    {
      name: "Sarah Johnson",
      timestamp: "2026-08-13T09:15:00Z",
      subject: "Project kickoff meeting",
      preview: "Let’s finalize the agenda for tomorrow’s kickoff session.",
      tags: ["Work", "Meeting"],
      unread: true,
    },
    {
      name: "Michael Chen",
      timestamp: "2026-08-13T08:42:00Z",
      subject: "Invoice attached",
      preview: "Please find the updated invoice for the August services.",
      tags: ["Finance"],
    },
    {
      name: "Emma Rodriguez",
      timestamp: "2026-08-13T07:30:00Z",
      subject: "Design feedback",
      preview: "I’ve added comments to the latest Figma file.",
      tags: ["Design"],
      unread: true,
    },
    {
      name: "David Kim",
      timestamp: "2026-08-12T18:10:00Z",
      subject: "Server maintenance",
      preview: "Maintenance is scheduled for Sunday at 2 AM.",
      tags: ["Infrastructure"],
    },
    {
      name: "Olivia Brown",
      timestamp: "2026-08-12T16:55:00Z",
      subject: "Client approval received",
      preview: "The client approved the revised proposal.",
      tags: ["Client", "Sales"],
    },
    {
      name: "James Wilson",
      timestamp: "2026-08-12T15:20:00Z",
      subject: "Weekly report",
      preview: "Here is the summary of this week’s progress.",
      tags: ["Work", "Report"],
    },
    {
      name: "Sophia Martinez",
      timestamp: "2026-08-12T14:05:00Z",
      subject: "New course content",
      preview: "The training videos have been uploaded.",
      tags: ["LMS"],
      unread: true,
    },
    {
      name: "Daniel Anderson",
      timestamp: "2026-08-12T13:40:00Z",
      subject: "Bug reproduction steps",
      preview: "I was able to reproduce the issue on Android.",
      tags: ["QA", "Bug"],
    },
    {
      name: "Ava Thompson",
      timestamp: "2026-08-12T12:18:00Z",
      subject: "Marketing assets",
      preview: "The social media banners are ready for review.",
      tags: ["Marketing"],
    },
    {
      name: "William Garcia",
      timestamp: "2026-08-12T11:02:00Z",
      subject: "Contract update",
      preview: "Legal has sent the updated agreement.",
      tags: ["Legal"],
    },
    {
      name: "Isabella Lee",
      timestamp: "2026-08-12T10:11:00Z",
      subject: "User interview notes",
      preview: "Sharing the key insights from today’s interviews.",
      tags: ["Research"],
    },
    {
      name: "Benjamin Harris",
      timestamp: "2026-08-12T09:27:00Z",
      subject: "Deployment successful",
      preview: "Production deployment completed without issues.",
      tags: ["DevOps"],
      unread: true,
    },
    {
      name: "Mia Clark",
      timestamp: "2026-08-11T17:45:00Z",
      subject: "Payment reminder",
      preview: "This is a reminder about the pending payment.",
      tags: ["Finance"],
    },
    {
      name: "Lucas Lewis",
      timestamp: "2026-08-11T16:30:00Z",
      subject: "API documentation",
      preview: "The authentication section has been updated.",
      tags: ["Backend", "Docs"],
    },
    {
      name: "Charlotte Walker",
      timestamp: "2026-08-11T15:14:00Z",
      subject: "Event registration",
      preview: "Your registration has been confirmed.",
      tags: ["Event"],
    },
    {
      name: "Henry Hall",
      timestamp: "2026-08-11T14:02:00Z",
      subject: "Database migration",
      preview: "Migration completed on the staging environment.",
      tags: ["Database"],
    },
    {
      name: "Amelia Allen",
      timestamp: "2026-08-11T13:26:00Z",
      subject: "Content approval",
      preview: "The blog post is approved for publishing.",
      tags: ["Content"],
    },
    {
      name: "Alexander Young",
      timestamp: "2026-08-11T12:09:00Z",
      subject: "Security review",
      preview: "Please review the latest security findings.",
      tags: ["Security"],
    },
    {
      name: "Harper Hernandez",
      timestamp: "2026-08-11T11:33:00Z",
      subject: "Customer feedback",
      preview: "Several users requested dark mode support.",
      tags: ["Customer"],
      unread: true,
    },
    {
      name: "Ethan King",
      timestamp: "2026-08-11T10:48:00Z",
      subject: "Sprint planning",
      preview: "Planning session starts at 3 PM.",
      tags: ["Agile"],
    },
    {
      name: "Evelyn Wright",
      timestamp: "2026-08-10T18:22:00Z",
      subject: "Recruitment update",
      preview: "We have shortlisted three candidates.",
      tags: ["HR"],
    },
    {
      name: "Matthew Lopez",
      timestamp: "2026-08-10T17:05:00Z",
      subject: "Performance metrics",
      preview: "Dashboard metrics have been refreshed.",
      tags: ["Analytics"],
    },
    {
      name: "Abigail Hill",
      timestamp: "2026-08-10T15:41:00Z",
      subject: "Partnership proposal",
      preview: "Please review the attached partnership draft.",
      tags: ["Business"],
    },
    {
      name: "Joseph Scott",
      timestamp: "2026-08-10T14:18:00Z",
      subject: "System outage report",
      preview: "Root cause analysis is now available.",
      tags: ["Incident"],
    },
    {
      name: "Ella Green",
      timestamp: "2026-08-10T13:07:00Z",
      subject: "UI polish",
      preview: "Minor spacing adjustments have been applied.",
      tags: ["Frontend"],
    },
    {
      name: "Samuel Adams",
      timestamp: "2026-08-10T11:52:00Z",
      subject: "Backup completed",
      preview: "All nightly backups finished successfully.",
      tags: ["Infrastructure"],
    },
    {
      name: "Grace Baker",
      timestamp: "2026-08-10T10:36:00Z",
      subject: "Feature request",
      preview: "Users are asking for offline access.",
      tags: ["Product"],
    },
    {
      name: "Christopher Nelson",
      timestamp: "2026-08-09T18:11:00Z",
      subject: "Vendor confirmation",
      preview: "The vendor confirmed the delivery schedule.",
      tags: ["Operations"],
    },
    {
      name: "Lily Carter",
      timestamp: "2026-08-09T16:49:00Z",
      subject: "Training session",
      preview: "Tomorrow’s session will cover advanced topics.",
      tags: ["Training"],
      unread: true,
    },
    {
      name: "Andrew Mitchell",
      timestamp: "2026-08-09T15:25:00Z",
      subject: "Final review",
      preview: "Everything is ready for final approval.",
      tags: ["Review"],
    },
  ];